/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArAmbulanceWlList {
    }
}
declare global {
    interface HTMLArAmbulanceWlListElement extends Components.ArAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLArAmbulanceWlListElement: {
        prototype: HTMLArAmbulanceWlListElement;
        new (): HTMLArAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "ar-ambulance-wl-list": HTMLArAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface ArAmbulanceWlList {
    }
    interface IntrinsicElements {
        "ar-ambulance-wl-list": ArAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ar-ambulance-wl-list": LocalJSX.ArAmbulanceWlList & JSXBase.HTMLAttributes<HTMLArAmbulanceWlListElement>;
        }
    }
}
